mysql:
  image: mysql:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=secret

ttrss:
  build: .
  environment:
    - DB_PORT=3306
    - DB_PASS=secret
    - DB_USER=root
  ports:
    - "8081:80"
  links:
    - mysql:db
